FROM alpine:3.13
<warning descr="Multiple consecutive 'RUN' instructions. Consider consolidation.">RUN pip install --no-cache-dir --upgrade pip</warning>
<warning descr="Multiple consecutive 'RUN' instructions. Consider consolidation.">RUN pip install --no-cache-dir --upgrade pip</warning>
USER mike
